export enum ContentType {
    JSON = "application/json",
    TEXT_PLAIN = "text/plain",
    TEXT_HTML = "text/html",
    TEXT_CSS = "text/css",
    TEXT_JAVASCRIPT = "text/javascript",
    APPLICATION_JAVASCRIPT = "application/javascript",
    APPLICATION_XML = "application/xml",
    APPLICATION_XHTML_XML = "application/xhtml+xml",
    APPLICATION_ATOM_XML = "application/atom+xml",
    APPLICATION_PDF = "application/pdf",
    APPLICATION_MSWORD = "application/msword",
    APPLICATION_OCTET_STREAM = "application/octet-stream",
    APPLICATION_VND_API_JSON = "application/vnd.api+json",
    APPLICATION_FORM_URLENCODED = "application/x-www-form-urlencoded",
    APPLICATION_ZIP = "application/zip",
    IMAGE_JPEG = "image/jpeg",
    IMAGE_PNG = "image/png",
    IMAGE_GIF = "image/gif",
    IMAGE_SVG_XML = "image/svg+xml",
    IMAGE_WEBP = "image/webp",
    MULTIPART_FORM_DATA = "multipart/form-data",
    AUDIO_MPEG = "audio/mpeg",
    AUDIO_OGG = "audio/ogg",
    VIDEO_MP4 = "video/mp4",
    VIDEO_MPEG = "video/mpeg",
    VIDEO_WEBM = "video/webm",
}
